### ISSUE TITLE
When buffering multiple geometries, get a TypeError

### ISSUE THREAD

**Issue by svmatthews** [cugos/drop-n-chop#1]
`Uncaught TypeError: Cannot set property 'properties' of undefined`

**Comment by morganherlocker** [comment]
If you have the geojson data that caused the error, open an issue on [turf-buffer](https://github.com/Turfjs/turf-buffer), and we can add a test fixture.

**Comment by alukach** [comment]
@svmatthews Can you post an example of an offending file to a [gist](gist.github.com) and link in here?

**Comment by svmatthews** [comment]
Hm, I posted this a while ago and can't seem to recreate. I'll make sure to bring it up if it happens again!

**Comment by alukach** [comment]
@svmatthews okay, no problem, I was thinking that it may be related to this similar issue that I was running into: https://github.com/Turfjs/turf-buffer/issues/22 .  Upgrading `turf-buffer` seemed to do the trick.

Forward thinking note: I think it's going to be import for this project to quickly identify whether an issue is a `drop-n-chop` issue or a `turf.js` issue and post issues accordingly.  Maybe, if a `turf.js` is is identified within `drop-n-chop`, it could be noted with this repo but only point to the issue in the appropriate `turf.js` repo?
