### ISSUE TITLE
Buffering pts re-add all .geojson layers

### ISSUE THREAD

**Issue by zeuzruse** [cugos/drop-n-chop#103]
Everytime I try to buffer the pts, all the pre-existing layers are re-added and all of them are visible.

**Comment by eldang** [comment]
I'm getting what I suspect is a related error:

1. Add a GeoJSON
2. Give it a buffer
3. Add another GeoJSON

At this point, I find the buffer from step 2 gets duplicated, and at least one is displayed.

**Comment by alukach** [comment]
I believe that this is related to #64

**Comment by eldang** [comment]
Looks likely to me.  I haven't yet found a pair of geojsons I can successfully union, so I can't do a perfect replication, but I think it is the same thing going on.

**Comment by alukach** [comment]
Yeah, I think the fact that the examples are both using `union` is just a coincidence. I believe that it occurs with any operation.

ps. Here are some union-able files: https://gist.github.com/alukach/0bf4471e44a0243b66db
