### ISSUE TITLE
Dropzone should be entire screen 

### ISSUE THREAD

**Issue by hamhands** [cugos/drop-n-chop#13]
Instead of dropzone only being on the left side, make it the entire screen to avoid this: 
![new](https://cloud.githubusercontent.com/assets/3640800/6882534/0066a6d8-d545-11e4-9580-a4ce12096ecf.gif)

**Comment by svmatthews** [comment]
Agreed! Maybe the entire `window` can be the dropzone, just adding a drop handler on that. Will do some testing here.
