### ISSUE TITLE
Build error handler and notification system

### ISSUE THREAD

**Issue by svmatthews** [cugos/drop-n-chop#25]
I'd like to start finding and standardizing potential errors that a user could run into (i.e. "incorrect file type", or "cannot union these two geometries"). I think logging errors is fine right away, but I'd like to connect it to a notification system within the application that is used for alerts/successes/etc. 

There are some libraries that do this, such as [notify.js](http://notifyjs.com/). Honestly, I think I might roll our own because this seems like a fantastic UI exercise.

**Comment by alukach** [comment]
I believe that #33 solved this (used to demonstrate errors in #97).
