### ISSUE TITLE
Set `gh-pages` as default branch

### ISSUE THREAD

**Issue by alukach** [cugos/drop-n-chop#28]
I've created a `gh-pages` branch, making the project available at http://cugos.org/drop-n-chop/. This should be made the default branch (https://github.com/cugos/drop-n-chop/settings), as all PRs should be folded into this branch.  Only members of the "Owners" group have the permissions to do this.

**Comment by svmatthews** [comment]
Nice. I'm honestly fine with the `master` branch being the default and just keeping `gh-pages` in the background for when we want to push updates to the live site. I envision us not **always** pushing to the live site while we work and then just dumping updates into it. Does that seem weird?

**Comment by alukach** [comment]
I think we're both in agreement that the `gh-pages` should be the gold standard (prod).

With that said, I've lately become more into being strict on PRs and merging straight into prod. Basically, a PR shouldn't be merged until it's assured that it's good to go.  Furthermore, every commit into prod should represent a safe/complete point in the codebase (this often requires that PRs get rebased into a single commit before being merged).  I like the freedom of being able to deploy to prod multiple times a day without a lot of process (with good tests and code reviews, each PR should be trustworthy).  I don't really see this as a project that will require versioning, I'd prefer a rolling release.  

It gets a bit messy though when we have `dist/` involved.  There will be `dist/` deconflictions that will be necessary (typically I think that will involve merging, blowing `dist/` away, recompiling, commiting new `dist`, push).  This kind of makes the dream of "merge PR to prod" a bit unrealistic at the projects current state.  What would be nice is if we could get a Travis like service to somehow continually merges prod into PR locally after each commit to the PR, delete `dist/`, build new `dist/` from PR + master, committing that `dist/` to the PR branch.  I don't know if that service exists (or if it's even a good idea).

So, yeah, until that is figured out, I agree with you that setting `gh-pages` as default is not the correct step.  Will close for now.

**Comment by svmatthews** [comment]
Gosh, I keep running into git status issues because of `/dist` rebuilds being built every time. I'm wondering if it makes most sense to `.gitignore` everything in `/dist` and then builds only get followed in the `gh-pages` branch.
