### ISSUE TITLE
Let's choose a javascript spec and set some options in the linter

### ISSUE THREAD

**Issue by svmatthews** [cugos/drop-n-chop#37]
such as 2 space indents, no semi-colons, `for/length` prioritized over `for/in`, etc.

**Comment by svmatthews** [comment]
### For loops

Use `for ( x in y ) { ... }` when working with objects.
Use `for (var x; x < y.length; x++ ) { ... }` when working with arrays.

Thoughts?

**Comment by svmatthews** [comment]
Eh, this seems overly detailed for now.

**Comment by alukach** [comment]
Yeah, maybe we can just say that we aim to use the [Google JavaScript Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml)?  I find that Google's guides are usually pretty complete and agreeable.  [AirBnB's Guide](https://github.com/airbnb/javascript) is popular but pretty short (doesn't cover that for-loops topic, for example).

**Comment by svmatthews** [comment]
:+1:
