### ISSUE TITLE
create script that builds from source and pushes into production

### ISSUE THREAD

**Issue by svmatthews** [cugos/drop-n-chop#38]
Now that we aren't watching `/dist` from #34 it would be good to get a shell script or some sort of automated way of building from the `master` branch and pushing into `gh-pages` for the production site. This presumably would only work for those who have write access and if they actually ran the script themselves. What does that workflow look like?

**Comment by alukach** [comment]
I've actually got this 90% of the way done: https://github.com/alukach/drop-n-chop/blob/master/.travis.yml  .  The intended feature is to build the project and deploy it to the `gh-pages` branch at the end of every successful Travis build on `master`.

**Comment by svmatthews** [comment]
I had no idea you could run things `after_success` in Travis. That's really neat! Also removes the whole step of one of us needing to run the script manually from our machines. Nice work!

**Comment by alukach** [comment]
Fixed in #44
