### ISSUE TITLE
Make ability to have grunt build release and dev instances of project

### ISSUE THREAD

**Issue by aaronr** [cugos/drop-n-chop#45]
There is no current way (other than modifying a tracked index.html file) to change to use non-minified versions of the code.  Also the index.html file is not placed in the dist dir like it should.  I understand that there where reasons to do this... but there must be a better way:

1) Have index.html end up in dist like the rest of the project when built.

2) Change the gh-pages stuff to just publish the contents of dist.
  - This gets rid of all the extra stuff that is being published that should not be (config files etc)
  - Everything is at the right level then (i.e. index.html is no longer treated special)

3) Make index.html based on a template in the root folder, but use a grunt html processor to build out the real index.html based on build type.  Some possible grunt tools already exist:
  - https://github.com/spatools/grunt-html-build
  - https://github.com/dciccale/grunt-processhtml

4) Make grunt serve and the connect stuff for grunt serve from the dist dir.

In the end you would be able to specify build type... each would pre-process the index.html to the proper form, populate the dist dir, and if updating master push a release version of the dist dir to gh-pages.

I plan to work on prototyping this (as a learning exercise for myself) in the aaronr_gruntwork branch

**Comment by alukach** [comment]
+1 to being able to develop off of `L.DNC.js` and serve off of `L.DNC.min.js`, the uglified file definitely takes some fun out of the dev process.  My $0.02: I think what would make this the easiest/most-natural-to-develop-on would be to have the dev folder hierarchy match what we want the prod folder to be (starting with moving `index.html` into `src/index.html`). Basically, any assets that would make their way into prod should go into `src`. Is this kind of along the lines of what you were thinking?

Also, in the event that you haven't already looked into it, the solution to #2 is super trivial (assuming #44 is merged), you would only need to change the [`base`](https://github.com/cugos/drop-n-chop/pull/44/files#diff-35b4a816e0441e6a375cd925af50752cR73) arg to point to `dist/`.

**Comment by svmatthews** [comment]
:+1: to all of this. Take it away @aaronr!

**Comment by alukach** [comment]
Fixed in #48
