### ISSUE TITLE
Remove References from Unrelated Components

### ISSUE THREAD

**Issue by thebigspoon** [cugos/drop-n-chop#52]
I would appreciate some feedback about the ideas I mention below and some of the solutions the commits tied to this ticket propose.

### The App/Controller Idea
Originally the `MapView` class was called something like `DncApp` and it's general purpose was to glue and setup things:
- setup and bind components being used in DNC, like the map
- setup component event listeners, like for `FileReader` event handlers
- it was a place for slim applciation logic, but not component specific stuff

When we decided that `MapView` felt like it was it's own component, things got shuffled around and some glue stuff didn't make sense to have in that class anymore.

I've noticed that some of the glue logic was moved out into `L.DNC` where it currently lives. My guess is that we can expect that `glue` to grow in the future. `L.DNC` really feels like a simple namespace object for things to hang off, but not it's own class. Maybe that's just me.

More importantly, another side effect of the refactor was the propagation of some patterns that I feel like we should avoid:
- `FileReader` now reaches outside of it's scope globally to access other components [here](https://github.com/cugos/drop-n-chop/blob/master/src/js/dropzone/handlers/DropZone.FileReader.js#L30-L31).
- The `TurfOperation` also reaches outside of it's scope to add layers [here](https://github.com/cugos/drop-n-chop/blob/master/src/js/menu/operations/TurfOperation.js#L30).
- Even more confusing, the `FileReader` component fires an event that it itself listens to [here](https://github.com/cugos/drop-n-chop/blob/master/src/js/dropzone/handlers/DropZone.FileReader.js#L24-L32). 

### Proposal
It feels like we need a thing that does the glueing and setup again. This thing, lets call it a controller, would also hold component references so we don't force components that shouldn't know about each other to tightly reference each other.

*What Changed?*
- I managed to remove all these type of references except [one](https://github.com/cugos/drop-n-chop/blob/remove-reflexive-refs/src/js/menu/operations/TurfOperation.js#L14-L23), which I flagged as a possible removal later. 
- For lack of a better term ( i'm open to anything ), I called the controller `AppController`. See the [class here](https://github.com/cugos/drop-n-chop/blob/remove-reflexive-refs/src/js/controller/AppController.js).

**Comment by alukach** [comment]
Interesting thoughts, will look more into the proposals soon.  Out of curiosity, why is this an Issue? Maybe we should just close this and move it all into the Pull Request?  I typically think of Issues as TODOs.

**Comment by thebigspoon** [comment]
I can do that. I write issues for every PR, it's just my thang
