### ISSUE TITLE
dist is showing up again, wtf!?

### ISSUE THREAD

**Issue by svmatthews** [cugos/drop-n-chop#60]
Our `dist/` directory is showing up again ... not sure why??

**Comment by aaronr** [comment]
Looks like you added them back in :-)

https://github.com/cugos/drop-n-chop/commit/666492358e8084941572ac71039d313f07e35870

**Comment by svmatthews** [comment]
Heh, of course. Any idea why it wasn't prevented even with the `.gitignore` ?

**Comment by svmatthews** [comment]
Well, removed it in 9226e6b4a594277e4218ac469fb88575245a1fb4 - hopefully doesn't pop up again.

**Comment by aaronr** [comment]
well... I could think of two things (maybe):

1) (unlikely) You used a --force on the add?  In that case it would override the .gitignore

2) Somehow you added the files (dist) in your branch (or whereever you where working), then merged in the change to the .gitignore from master, then merged the whole ball back into master from your branch.  If your /dist folder had diverged from master then they would have still been tracked.  Then you would run into the situation of the .gitignore being changed after the ignored files had changed which is a well documented state of chaos:

http://jlordiales.me/2012/12/28/when-git-ignores-your-gitignore/

I think we had done a git rm on the files in that dir, but maybe we need to look at this git rm --cached which I have never used.

Hopefully this does not happen again, but I bet it is from merging something pre-change to the .gitignore.

**Comment by svmatthews** [comment]
That `notifications` branch is pretty old and, in fact, was created just hours before @alukach added `dist/` to be ignored. Confirmed with the timestamps!

![screen shot 2015-04-27 at 1 58 24 pm](https://cloud.githubusercontent.com/assets/1943001/7357782/cf0e04e2-ece5-11e4-8acb-12bc47077b93.png)
![screen shot 2015-04-27 at 1 58 57 pm](https://cloud.githubusercontent.com/assets/1943001/7357781/cf0ce49a-ece5-11e4-9ec6-2c651a81041f.png)
