### ISSUE TITLE
Get rid of Ruby dependency.  Find a NodeJS Sass compiler.

### ISSUE THREAD

**Issue by thedeb** [cugos/drop-n-chop#99]
Grunt errors when Ruby and Sass are not installed. This dependency is (could be) unnecessary.

**Comment by eldang** [comment]
Good idea. Does https://github.com/sass/node-sass do what this project needs?  (I don't know enough about the system to answer that yet)

**Comment by npeihl** [comment]
:+1:

**Comment by ksymer** [comment]
+1

**Comment by westyvw** [comment]
Remove it
+1

**Comment by andybell** [comment]
+1 https://github.com/sass/node-sass

**Comment by svmatthews** [comment]
https://github.com/sindresorhus/grunt-sass should also be libsass based and not ruby based like grunt-contrib-sass

**Comment by svmatthews** [comment]
Hi all! This should be fixed now from #109 - you'll want to run `npm install` again to update your dependencies with this new SASS compiler.
